"""
Phase 2 → Phase 1b Alignment Test

Captures the NPU instruction stream generated by Phase 2 firmware
(via ISS + TraceRecorder) and replays it through Phase 1b's NpuFP32,
verifying that both produce identical logits.
"""

import numpy as np
import pytest

from emulator.npu_device_mini import MEM_DRAM
from emulator.trace_recorder import TraceRecorder
from emulator.npu_fp32 import NpuFP32
from adderboard.layout.layout_130p import (
    build_dram, encode_prompt, decode_output,
    dram_addr, MODEL_DIM, HEAD_DIM,
    OUTPUT_DIGITS, VOCAB_SIZE,
)
from adderboard.tests._test_130p_phase2 import (
    _build_firmware, make_npu,
    S_X, S_CTX, S_MLP_OUT, S_AFTER_MLP,
    S_MASK_H0, S_MASK_H1, S_MASK_TABLE,
    FW_LAST_H, MAX_SEQ,
)
from adderboard.golden.golden_130p import forward as golden_forward

try:
    from iss.mini_rv64 import MiniRV64
    HAS_ISS = True
except ImportError:
    HAS_ISS = False
    MiniRV64 = None


def run_and_capture(dram, tokens):
    """Run Phase 2 firmware, return (logits, npu, inst_trace, dram_w, srf_w)."""
    T = len(tokens)
    r, elf_path = _build_firmware(4, seq_len=T)
    if r.returncode != 0 or not elf_path.exists():
        raise RuntimeError(f"Firmware build failed:\n{r.stderr[:500]}")

    inner = make_npu(dram)
    npu = TraceRecorder(inner)

    # Set up scratch (same as test_phase2_iss)
    for i in range(T):
        npu._vrf[MEM_DRAM][S_X + i * MODEL_DIM:
                           S_X + (i + 1) * MODEL_DIM] = \
            np.array([float(tokens[i]), 0.0, 0.0, 0.0], dtype=np.float32)
    npu._vrf[MEM_DRAM][S_MASK_H0:S_MASK_H0 + MODEL_DIM] = np.array(
        [1.0, 1.0, 0.0, 0.0], dtype=np.float32)
    npu._vrf[MEM_DRAM][S_MASK_H1:S_MASK_H1 + MODEL_DIM] = np.array(
        [0.0, 0.0, 1.0, 1.0], dtype=np.float32)

    nt = (T + 3) // 4
    mt = S_MASK_TABLE
    for q in range(T):
        for tc in range(nt):
            base = tc * 4
            valid = min(4, T - base)
            mask = np.full(4, -1e30, dtype=np.float32)
            for p in range(valid):
                if base + p <= q:
                    mask[p] = 0.0
            addr = mt + (q * nt + tc) * MODEL_DIM
            npu._vrf[MEM_DRAM][addr:addr + MODEL_DIM] = mask

    from adderboard.golden.golden_130p import _load_weights
    w = _load_weights(dram if dram.dtype == np.float32
                       else np.frombuffer(dram, dtype=np.float32))
    x = np.zeros((T, MODEL_DIM), dtype=np.float32)
    for i in range(T):
        x[i] = w['embed_A'][tokens[i]] * w['embed_B'] + w['pe_table'][i]
    qkv = x @ w['c_attn'].T
    v = qkv[:, 2 * MODEL_DIM:3 * MODEL_DIM]

    svt = mt + MAX_SEQ * nt * MODEL_DIM
    for tc in range(nt):
        base = tc * 4
        valid = min(4, T - base)
        vt = np.zeros((MODEL_DIM, MODEL_DIM), dtype=np.float32)
        for p in range(valid):
            pos = base + p
            for d in range(MODEL_DIM):
                vt[d, p] = v[pos, d]
        tile_addr = svt + tc * MODEL_DIM * MODEL_DIM
        for d in range(MODEL_DIM):
            npu._vrf[MEM_DRAM][tile_addr + d * MODEL_DIM:
                                tile_addr + (d + 1) * MODEL_DIM] = vt[d]

    npu._spu_srf[6] = 2.0 ** -0.5
    npu.set_seq_len(T)

    cpu = MiniRV64()
    cpu.set_mmio_device(npu)
    cpu.load_elf(str(elf_path))
    cpu.run(cycles=500000)

    last_h = inner._vrf[MEM_DRAM][FW_LAST_H:FW_LAST_H + MODEL_DIM].copy()
    lm_v = inner._vrf[MEM_DRAM][dram_addr('lm_v'):dram_addr('lm_v') + MODEL_DIM].copy()
    lm_u = inner._vrf[MEM_DRAM][dram_addr('lm_u'):dram_addr('lm_u') + VOCAB_SIZE].copy()
    lm_b = inner._vrf[MEM_DRAM][dram_addr('lm_bias'):dram_addr('lm_bias') + VOCAB_SIZE].copy()
    proj = float(np.dot(last_h, lm_v))
    logits = proj * lm_u + lm_b
    return logits, inner, npu.inst_trace, npu.dram_writes, npu.srf_writes


def replay_on_npufp32(dram, tokens, inst_trace, dram_w, srf_w):
    """Replay captured instruction stream + MMIO exchanges on NpuFP32."""
    T = len(tokens)
    npu = NpuFP32()
    npu.load_dram(dram)

    # Same scratch setup as run_and_capture
    for i in range(T):
        npu._vrf[MEM_DRAM][S_X + i * MODEL_DIM:S_X + (i+1) * MODEL_DIM] = \
            np.array([float(tokens[i]), 0.0, 0.0, 0.0], dtype=np.float32)
    npu._vrf[MEM_DRAM][S_MASK_H0:S_MASK_H0 + MODEL_DIM] = np.array(
        [1.0, 1.0, 0.0, 0.0], dtype=np.float32)
    npu._vrf[MEM_DRAM][S_MASK_H1:S_MASK_H1 + MODEL_DIM] = np.array(
        [0.0, 0.0, 1.0, 1.0], dtype=np.float32)

    nt = (T + 3) // 4
    mt = S_MASK_TABLE
    for q in range(T):
        for tc in range(nt):
            base = tc * 4
            valid = min(4, T - base)
            mask = np.full(4, -1e30, dtype=np.float32)
            for p in range(valid):
                if base + p <= q:
                    mask[p] = 0.0
            addr = mt + (q * nt + tc) * MODEL_DIM
            npu._vrf[MEM_DRAM][addr:addr + MODEL_DIM] = mask

    from adderboard.golden.golden_130p import _load_weights
    w = _load_weights(dram if dram.dtype == np.float32
                       else np.frombuffer(dram, dtype=np.float32))
    x = np.zeros((T, MODEL_DIM), dtype=np.float32)
    for i in range(T):
        x[i] = w['embed_A'][tokens[i]] * w['embed_B'] + w['pe_table'][i]
    qkv = x @ w['c_attn'].T
    v = qkv[:, 2 * MODEL_DIM:3 * MODEL_DIM]

    svt = mt + MAX_SEQ * nt * MODEL_DIM
    for tc in range(nt):
        base = tc * 4
        valid = min(4, T - base)
        vt = np.zeros((MODEL_DIM, MODEL_DIM), dtype=np.float32)
        for p in range(valid):
            pos = base + p
            for d in range(MODEL_DIM):
                vt[d, p] = v[pos, d]
        tile_addr = svt + tc * MODEL_DIM * MODEL_DIM
        for d in range(MODEL_DIM):
            npu._vrf[MEM_DRAM][tile_addr + d * MODEL_DIM:
                                tile_addr + (d + 1) * MODEL_DIM] = vt[d]

    npu._spu_srf[6] = 2.0 ** -0.5
    npu._spu_srf[4] = 0.0

    # Apply ALL DRAM writes BEFORE instructions (pre-populate MLP_OUT)
    # These happen between NPU instruction batches (after npu_wait_done).
    for float_off, raw in dram_w:
        val = np.frombuffer(raw.to_bytes(4, 'little'), dtype=np.float32)[0]
        npu._vrf[MEM_DRAM][float_off] = val

    # Replay instructions with interleaved SRF writes.
    # The firmware zeros SRF[1] via MMIO before each (q,head)'s Pass 2.
    # Pattern: 1 SPU_ADD_REDUCE(-inf) to SRF[0], 6 SPU_MAX_REDUCE to SRF[0],
    # then MMIO zero SRF[1], then 6 SPU_ADD_REDUCE to SRF[1].
    # Track max_reduce_count within each (q,head) pair.
    srf_idx = 0
    max_count = 0
    for inst in inst_trace:
        opcode = (inst >> 24) & 0xFF
        opd0 = (inst >> 16) & 0xFF
        opd1 = inst & 0xFFFF

        npu.send(inst)

        # After the 6th SPU_MAX_REDUCE to SRF[0], apply next SRF write
        if opcode == 5 and opd0 == 15 and opd1 == 0:  # SPU_MAX_REDUCE(0)
            max_count += 1
            if max_count == 6 and srf_idx < len(srf_w):
                idx, raw = srf_w[srf_idx]
                val = np.frombuffer(raw.to_bytes(4, 'little'),
                                     dtype=np.float32)[0]
                npu._spu_srf[idx] = val
                srf_idx += 1
                max_count = 0

        # SPU_ADD_REDUCE(-inf) to SRF[0] resets the counter
        if opcode == 5 and opd0 == 14 and opd1 == 0:
            max_count = 0

    # Debug output
    print(f"  Replay SRF[0]={npu._spu_srf[0]:.4f} SRF[1]={npu._spu_srf[1]:.4f} SRF[2]={npu._spu_srf[2]:.6f}")
    print(f"  Replay CTX[9]={npu.get_dram(S_CTX+9*4, 4)}")
    print(f"  Replay CTX[10]={npu.get_dram(S_CTX+10*4, 4)}")

    # Read last_h and compute logits
    last_h = npu.get_dram(FW_LAST_H, MODEL_DIM)
    lm_v = npu.get_dram(dram_addr('lm_v'), MODEL_DIM)
    lm_u = npu.get_dram(dram_addr('lm_u'), VOCAB_SIZE)
    lm_b = npu.get_dram(dram_addr('lm_bias'), VOCAB_SIZE)
    proj = float(np.dot(last_h, lm_v))
    logits = proj * lm_u + lm_b
    return logits, npu


GOLDEN_DRAM = None


def _get_dram():
    global GOLDEN_DRAM
    if GOLDEN_DRAM is None:
        GOLDEN_DRAM, _ = build_dram()
    return GOLDEN_DRAM


@pytest.mark.skipif(not HAS_ISS, reason="ISS not available")
def test_phase2_replay_on_phase1b_first_step():
    dram = _get_dram()
    a, b = 5, 5
    tokens = encode_prompt(a, b)
    gl = golden_forward(dram, tokens)

    fw_logits, fw_npu, inst_trace, dram_w, srf_w = run_and_capture(dram, tokens)
    rp_logits, rp_npu = replay_on_npufp32(dram, tokens, inst_trace, dram_w, srf_w)

    fw_diff = float(np.max(np.abs(gl - fw_logits)))
    rp_diff = float(np.max(np.abs(gl - rp_logits)))

    print(f"Instruction count: {len(inst_trace)}")
    print(f"FW logits:  {fw_logits}")
    print(f"RP logits:  {rp_logits}")
    print(f"Golden:     {gl}")
    print(f"FW vs golden max diff:  {fw_diff:.6f}")
    print(f"RP vs golden max diff:  {rp_diff:.6f}")

    assert fw_diff < 1e-3, f"Firmware diverges from golden: {fw_diff}"
    assert rp_diff < 1e-3, f"Replay diverges from golden: {rp_diff}"
    assert np.argmax(fw_logits) == np.argmax(rp_logits), (
        f"Argmax mismatch: FW={np.argmax(fw_logits)}, RP={np.argmax(rp_logits)}")
    print("✅  Phase 2 instruction stream replays correctly on Phase 1b NpuFP32")


@pytest.mark.skipif(not HAS_ISS, reason="ISS not available")
@pytest.mark.parametrize("a,b,expected", [
    (5, 5, 10),
    (555, 445, 1000),
    (0, 0, 0),
])
def test_phase2_replay_autoregressive(a, b, expected):
    dram = _get_dram()
    tokens = encode_prompt(a, b)

    for step in range(OUTPUT_DIGITS):
        fw_logits, fw_npu, inst_trace, dram_w, srf_w = run_and_capture(dram, tokens)
        rp_logits, rp_npu = replay_on_npufp32(dram, tokens, inst_trace, dram_w, srf_w)

        diff = float(np.max(np.abs(fw_logits - rp_logits)))
        assert diff < 1e-3, (
            f"Step {step}: FW vs RP logit diff {diff:.6f}")
        next_tok = int(np.argmax(fw_logits))
        tokens.append(next_tok)

    result = decode_output(tokens)
    assert result == expected, f"Result {result} != expected {expected}"
    print(f"  ✅  {a} + {b} = {result}")
